use clap::Args;
use std::path::PathBuf;

#[derive(Args)]
pub struct InitArgs {
    /// Path to initialize (defaults to current directory)
    #[arg(long, short, default_value = ".")]
    pub path: PathBuf,

    /// Force reinitialize even if already initialized
    #[arg(long)]
    pub force: bool,

    /// Preview initialization without writing files
    #[arg(long)]
    pub dry_run: bool,

    /// Output as JSON
    #[arg(long)]
    pub json: bool,
}

#[derive(serde::Serialize)]
struct InitResult {
    initialized: bool,
    dry_run: bool,
    path: String,
    created_dirs: Vec<String>,
    created_files: Vec<String>,
    already_existed: Vec<String>,
}

pub async fn run(args: InitArgs) -> anyhow::Result<()> {
    let root = args
        .path
        .canonicalize()
        .unwrap_or_else(|_| args.path.clone());
    let altevra_dir = root.join(".altevra");

    let mut created_dirs = vec![];
    let mut created_files = vec![];
    let mut already_existed = vec![];

    // Create directory structure
    let dirs = [
        altevra_dir.join("vault"),
        altevra_dir.join("events"),
        root.join("06-skills"),
        root.join("07-capabilities"),
        root.join("15-generated/setup-packs"),
    ];

    for dir in &dirs {
        if dir.exists() {
            already_existed.push(dir.display().to_string());
        } else {
            if !args.dry_run {
                std::fs::create_dir_all(dir)?;
            }
            created_dirs.push(dir.display().to_string());
        }
    }

    // Create default config
    let config_path = altevra_dir.join("config.toml");
    if !config_path.exists() || args.force {
        if !args.dry_run {
            let config = include_default_config();
            std::fs::write(&config_path, config)?;
        }
        created_files.push(config_path.display().to_string());
    } else {
        already_existed.push(config_path.display().to_string());
    }

    // Create default hooks.yaml
    let hooks_path = root.join("07-capabilities/hooks.yaml");
    if !hooks_path.exists() || args.force {
        if !args.dry_run {
            std::fs::write(&hooks_path, default_hooks_yaml())?;
        }
        created_files.push(hooks_path.display().to_string());
    } else {
        already_existed.push(hooks_path.display().to_string());
    }

    // Create default agent-tools.yaml
    let tools_path = root.join("07-capabilities/agent-tools.yaml");
    if !tools_path.exists() || args.force {
        if !args.dry_run {
            std::fs::write(&tools_path, default_agent_tools_yaml())?;
        }
        created_files.push(tools_path.display().to_string());
    } else {
        already_existed.push(tools_path.display().to_string());
    }

    let result = InitResult {
        initialized: !args.dry_run,
        dry_run: args.dry_run,
        path: root.display().to_string(),
        created_dirs,
        created_files,
        already_existed,
    };

    if args.json {
        println!("{}", serde_json::to_string_pretty(&result)?);
    } else {
        if args.dry_run {
            println!("Altevra init dry-run at: {}", root.display());
        } else {
            println!("Altevra initialized at: {}", root.display());
        }
        if !result.created_dirs.is_empty() {
            let label = if args.dry_run {
                "Directories to create"
            } else {
                "Created directories"
            };
            println!("\n{label}:");
            for d in &result.created_dirs {
                println!("  + {d}");
            }
        }
        if !result.created_files.is_empty() {
            let label = if args.dry_run {
                "Files to create"
            } else {
                "Created files"
            };
            println!("\n{label}:");
            for f in &result.created_files {
                println!("  + {f}");
            }
        }
        if !result.already_existed.is_empty() {
            println!("\nAlready existed (skipped):");
            for e in &result.already_existed {
                println!("  ~ {e}");
            }
        }
        if args.dry_run {
            println!("\nDry-run only: no files were written.");
        }
        println!("\nNext: altevra connect --tool claude-code --project <name> --dry-run");
    }

    Ok(())
}

fn include_default_config() -> String {
    r#"# Altevra Configuration
# Generated by: altevra init

[database]
# Set ALTEVRA_DATABASE_URL or configure here
url = "postgres://localhost/altevra"
max_connections = 10

[vault]
# Path to the Altevra vault directory
# Defaults to current directory (.)
path = "."

[altevra]
version = "0.1.0"
"#
    .to_string()
}

fn default_hooks_yaml() -> &'static str {
    r#"# Altevra Universal Hooks
# Generated by: altevra init
# ALTEVRA_MANAGED: true

hooks:
  - slug: session_start
    version: "0.1.0"
    hook_type: session_start
    enabled: true
    actions:
      - check_skill_version
      - get_last_updates
      - get_project_context
      - start_session_log
    description: "Bootstrap agent context at session start."

  - slug: session_end
    version: "0.1.0"
    hook_type: session_end
    enabled: true
    actions:
      - end_session_log
      - emit_event
    description: "Finalize session log and emit session_ended event."

  - slug: on_error
    version: "0.1.0"
    hook_type: on_error
    enabled: true
    actions:
      - emit_event
      - create_review_item
    description: "Log errors as events and create review items."
"#
}

fn default_agent_tools_yaml() -> &'static str {
    r#"# Altevra Agent Tools Capability Matrix
# Generated by: altevra init
# ALTEVRA_MANAGED: true

tools:
  - name: claude-code
    adapter: claude_code
    supports_native_hooks: true
    supports_mcp: true
    supports_skills: true
    supports_instructions: true
    notes: "Full adapter support. Use altevra connect --tool claude-code."

  - name: codex
    adapter: codex
    supports_native_hooks: false
    supports_mcp: false
    supports_skills: true
    supports_instructions: true
    notes: "CLI fallback only. AGENTS.md instructions."

  - name: cursor
    adapter: cursor
    supports_native_hooks: false
    supports_mcp: false
    supports_skills: true
    supports_instructions: true
    notes: ".cursor/rules/ based. CLI fallback for hooks."

  - name: aider
    adapter: aider
    supports_native_hooks: false
    supports_mcp: false
    supports_skills: true
    supports_instructions: true
    notes: "CONVENTIONS.md based."
"#
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[tokio::test]
    async fn test_init_creates_structure() {
        let tmp = TempDir::new().unwrap();
        let args = InitArgs {
            path: tmp.path().to_path_buf(),
            force: false,
            dry_run: false,
            json: false,
        };
        run(args).await.unwrap();

        assert!(tmp.path().join(".altevra").exists());
        assert!(tmp.path().join(".altevra/vault").exists());
        assert!(tmp.path().join("06-skills").exists());
        assert!(tmp.path().join("07-capabilities").exists());
        assert!(tmp.path().join("07-capabilities/hooks.yaml").exists());
        assert!(tmp.path().join("07-capabilities/agent-tools.yaml").exists());
    }

    #[tokio::test]
    async fn test_init_json_output() {
        let tmp = TempDir::new().unwrap();
        let args = InitArgs {
            path: tmp.path().to_path_buf(),
            force: false,
            dry_run: false,
            json: true,
        };
        // Should not panic or error
        run(args).await.unwrap();
    }

    #[tokio::test]
    async fn test_init_idempotent() {
        let tmp = TempDir::new().unwrap();
        for _ in 0..2 {
            let args = InitArgs {
                path: tmp.path().to_path_buf(),
                force: false,
                dry_run: false,
                json: false,
            };
            run(args).await.unwrap();
        }
        // Second run should not fail
        assert!(tmp.path().join(".altevra").exists());
    }

    #[tokio::test]
    async fn test_init_dry_run_has_no_side_effects() {
        let tmp = TempDir::new().unwrap();
        let args = InitArgs {
            path: tmp.path().to_path_buf(),
            force: false,
            dry_run: true,
            json: false,
        };

        run(args).await.unwrap();

        assert!(!tmp.path().join(".altevra").exists());
        assert!(!tmp.path().join("06-skills").exists());
        assert!(!tmp.path().join("07-capabilities").exists());
        assert!(!tmp.path().join("15-generated").exists());
    }
}
