//! `altevra install-hooks` — the load-bearing one-shot that wires Altevra into
//! every AI tool Pavle uses (Claude Code, Codex, Cursor CLI, Hermes).
//!
//! ## Why this command exists
//!
//! Today Pavle has to hand-edit four different config files (each with its own
//! schema) to make Altevra see his sessions. This command does it once, safely,
//! additively (never deletes existing `imperium-emit` lines), with a backup
//! before every write and idempotent re-runs.
//!
//! ## Safety contract (CRITICAL)
//!
//! 1. **Backup before every write** — `cp <config> <config>.altevra-backup-<unix_ts>`,
//!    unconditionally, BEFORE parsing or modifying anything.
//! 2. **Additive only** — never delete existing entries. We append Altevra entries
//!    alongside whatever else is there (imperium-emit, herdr, gsd hooks, ...).
//! 3. **Self-skip (SI-6 — two layers)** —
//!    - **Global gate** — `run()` refuses entirely (with a `bail!`) when the
//!      current working directory is inside the Altevra workspace. This stops
//!      Pavle from accidentally wiring `$HOME/.claude/settings.json` (which
//!      lives OUTSIDE the repo) while sitting in the repo: those global hooks
//!      would fire during Altevra's own dev sessions and create a feedback
//!      loop. Override with `ALTEVRA_BYPASS_SELF_SKIP=1` only if you really
//!      mean it.
//!    - **Per-target check** — `is_altevra_repo_target()` additionally refuses
//!      when a *specific* target path is itself inside the Altevra workspace
//!      (e.g. smart-scope landing on the repo's own `.claude/settings.json`).
//!
//!    Both layers detect Altevra by *parsing* `Cargo.toml` — `[package].name`
//!    equals `altevra` or starts with `altevra-`, OR the file is a workspace
//!    root listing `altevra-*` members. Substring matches on raw text are
//!    forbidden because a downstream Cargo.toml may legitimately list
//!    `altevra = "x.y"` as a dependency.
//! 4. **Idempotent** — re-running with no changes does nothing; entries are
//!    identified by the `_altevra_managed: true` marker.
//! 5. **Drift = require --force** — if a managed entry exists with content that
//!    differs from what we'd write now, abort unless `--force` is passed.
//! 6. **Post-write validation** — re-parse the written file; on parse failure
//!    restore from backup.
//!
//! ## Schemas (one per tool)
//!
//! | Tool        | Path                    | Format | Schema                                                          |
//! |-------------|-------------------------|--------|-----------------------------------------------------------------|
//! | claude-code | `~/.claude/settings.json` | JSON   | `{hooks: {EventName: [{matcher, hooks: [{type, command, ...}]}]}}` |
//! | codex       | `~/.codex/hooks.json`     | JSON   | identical to claude-code                                        |
//! | cursor      | `~/.cursor/hooks.json`    | JSON   | v1: `{hooks: {eventName: [{command}]}}`, no matcher, camelCase  |
//! | hermes      | `~/.hermes/config.yaml`   | YAML   | `hooks: {event_name: [{command, timeout?}]}`, snake_case        |
//!
//! For Hermes we ALSO copy `altevra-ingest.sh` into `~/.hermes/hooks/` and chmod
//! 0755 — the bridge script generated by `altevra-adapters::hermes_ingest_sh`.
//!
//! ## Smart auto-scope (Pavle: "Altevra decides, not me")
//!
//! After global wire, we scan `~/.imperium/identity/projects.yaml` and
//! `~/projekti/` for git repos and score each. Repos with score >= 3 also get a
//! per-project `.claude/settings.json`. Decisions are logged to
//! `~/.altevra/install-hooks-decisions.log` for transparency.

use anyhow::{bail, Context as _, Result};
use clap::Args;
use serde_json::{json, Map, Value};
use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

/// Marker key embedded in every Altevra-written hook entry. Used for
/// idempotency (skip if present) and drift detection (compare commands).
pub const MANAGED_MARKER: &str = "_altevra_managed";

/// Tools we support. The CLI's `--tool` flag accepts these strings (or `all`).
const SUPPORTED_TOOLS: &[&str] = &["claude-code", "codex", "cursor", "hermes"];

/// Set this to `1` to override the SI-6 global self-skip gate (run from inside
/// the Altevra repo). Intended only for maintainers explicitly re-wiring after
/// a clean state — normal users should never need it.
const SELF_SKIP_BYPASS_ENV: &str = "ALTEVRA_BYPASS_SELF_SKIP";

#[derive(Args, Clone, Debug)]
pub struct InstallHooksArgs {
    /// Which tool to wire. Defaults to wiring all four.
    #[arg(long)]
    pub tool: Option<String>,

    /// Overwrite drifted Altevra-managed entries (entries whose command we'd
    /// change). Without `--force`, drift causes an abort with a clear message.
    #[arg(long)]
    pub force: bool,

    /// Print planned changes without touching any file.
    #[arg(long)]
    pub dry_run: bool,

    /// Override $HOME (used in tests so we never touch Pavle's real configs).
    #[arg(long, hide = true)]
    pub home: Option<PathBuf>,

    /// Override the smart-scope walk root (defaults to `$HOME/projekti`).
    /// Tests point this at a temp dir; real runs leave it None.
    #[arg(long, hide = true)]
    pub projects_root: Option<PathBuf>,

    /// Bypass the SI-6 global self-skip gate (run from inside the altevra
    /// repo). Equivalent to setting `ALTEVRA_BYPASS_SELF_SKIP=1`. Hidden flag
    /// intended for in-process tests that already operate against a TempDir
    /// HOME, so process-global env mutation isn't needed.
    #[arg(long, hide = true)]
    pub bypass_self_skip: bool,
}

/// Outcome of patching one tool's global config, returned for reporting.
#[derive(Debug, Clone, Default)]
pub struct PatchOutcome {
    pub tool: String,
    pub config_path: PathBuf,
    pub backup_path: Option<PathBuf>,
    pub added_events: Vec<String>,
    pub skipped_events: Vec<String>,
    pub drifted_events: Vec<String>,
    pub self_skipped: bool,
    pub dry_run: bool,
}

pub async fn run(args: InstallHooksArgs) -> Result<()> {
    let home = resolve_home(&args)?;
    let tools = resolve_tool_set(args.tool.as_deref())?;

    // SI-6 global self-skip gate: refuse the entire install when cwd is inside
    // the Altevra workspace. The per-target check below catches the case where
    // a *specific* target sits inside the repo, but the global config paths
    // ($HOME/.claude/settings.json etc.) live OUTSIDE the repo — so without
    // this gate, running `altevra install-hooks` from `~/projekti/.../altevra`
    // would happily patch global configs and create a feedback loop in
    // Altevra's own dev sessions.
    let bypass_self_skip = args.bypass_self_skip
        || std::env::var(SELF_SKIP_BYPASS_ENV).ok().as_deref() == Some("1");
    if let Some(repo_root) = detect_altevra_workspace_from_cwd() {
        let cwd = std::env::current_dir().ok();
        log_self_skip_decision(&home, repo_root.as_path(), cwd.as_deref(), bypass_self_skip);
        if !bypass_self_skip {
            bail!(
                "altevra install-hooks refuses to run from inside the altevra repo itself \
                 (SI-6 self-write exclusion). Detected workspace at {}. Run it from another \
                 directory or set {SELF_SKIP_BYPASS_ENV}=1 to override.",
                repo_root.display()
            );
        }
    }

    println!("altevra install-hooks");
    println!("  home: {}", home.display());
    println!("  tools: {}", tools.join(", "));
    println!("  mode: {}", if args.dry_run { "dry-run" } else { "apply" });
    println!();

    let mut outcomes = Vec::new();
    for tool in &tools {
        let outcome = match tool.as_str() {
            "claude-code" => patch_claude_code(&home, args.force, args.dry_run)?,
            "codex" => patch_codex(&home, args.force, args.dry_run)?,
            "cursor" => patch_cursor(&home, args.force, args.dry_run)?,
            "hermes" => patch_hermes(&home, args.force, args.dry_run)?,
            other => bail!("unknown tool '{other}'"),
        };
        print_outcome(&outcome);
        outcomes.push(outcome);
    }

    // Smart scope: only when wiring all (no --tool filter); never during dry-run.
    if args.tool.is_none() && !args.dry_run {
        let scope_root = args
            .projects_root
            .clone()
            .unwrap_or_else(|| home.join("projekti"));
        if scope_root.exists() {
            let decisions = smart_scope_apply(&home, &scope_root)?;
            println!("\nsmart-scope decisions: {} repos", decisions.len());
            for d in &decisions {
                println!("  - {} score={} action={}", d.path.display(), d.score, d.action);
            }
        }
    }

    Ok(())
}

fn print_outcome(o: &PatchOutcome) {
    println!("[{}]", o.tool);
    println!("  config: {}", o.config_path.display());
    if o.self_skipped {
        println!("  SELF-SKIP: detected altevra repo as the target — refusing to wire.");
        return;
    }
    if let Some(b) = &o.backup_path {
        println!("  backup: {}", b.display());
    }
    if !o.added_events.is_empty() {
        println!("  added: {}", o.added_events.join(", "));
    }
    if !o.skipped_events.is_empty() {
        println!("  already-managed (skipped): {}", o.skipped_events.join(", "));
    }
    if !o.drifted_events.is_empty() {
        println!(
            "  DRIFT (need --force to overwrite): {}",
            o.drifted_events.join(", ")
        );
    }
    if o.dry_run {
        println!("  (dry-run — no file written)");
    }
}

// ───────────────────────────────────────────────────────────────────────────
// Tool selection / home resolution
// ───────────────────────────────────────────────────────────────────────────

fn resolve_home(args: &InstallHooksArgs) -> Result<PathBuf> {
    if let Some(h) = &args.home {
        return Ok(h.clone());
    }
    let h = std::env::var("HOME").context("HOME not set")?;
    Ok(PathBuf::from(h))
}

fn resolve_tool_set(filter: Option<&str>) -> Result<Vec<String>> {
    match filter {
        None | Some("all") => Ok(SUPPORTED_TOOLS.iter().map(|s| s.to_string()).collect()),
        Some(one) if SUPPORTED_TOOLS.contains(&one) => Ok(vec![one.to_string()]),
        Some(other) => bail!(
            "unknown --tool '{other}'; supported: {}",
            SUPPORTED_TOOLS.join(", ")
        ),
    }
}

// ───────────────────────────────────────────────────────────────────────────
// Backup helper (unconditional, BEFORE any write)
// ───────────────────────────────────────────────────────────────────────────

/// Copy `path` to `path.altevra-backup-<unix_ts>` so any future write is
/// recoverable. If the source doesn't exist (first-time install), we return
/// `None` (nothing to back up).
fn backup_file(path: &Path) -> Result<Option<PathBuf>> {
    if !path.exists() {
        return Ok(None);
    }
    let ts = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    let backup = path.with_extension(format!(
        "{}.altevra-backup-{}",
        path.extension().and_then(|s| s.to_str()).unwrap_or(""),
        ts
    ));
    fs::copy(path, &backup).with_context(|| {
        format!("failed to back up {} → {}", path.display(), backup.display())
    })?;
    Ok(Some(backup))
}

/// Restore `path` from `backup` on any post-write validation failure.
fn restore_from_backup(path: &Path, backup: &Path) -> Result<()> {
    fs::copy(backup, path)
        .with_context(|| format!("failed to restore {} from {}", path.display(), backup.display()))?;
    Ok(())
}

// ───────────────────────────────────────────────────────────────────────────
// Event matrices
// ───────────────────────────────────────────────────────────────────────────

/// Claude Code / Codex event matrix: (EventName, altevra-event-arg).
fn claude_event_matrix() -> &'static [(&'static str, &'static str)] {
    &[
        ("SessionStart", "session_start"),
        ("UserPromptSubmit", "user_prompt_submit"),
        ("PreToolUse", "pre_tool_use"),
        ("PostToolUse", "post_tool_use"),
        // Claude Code fires `Stop` after EVERY assistant turn, NOT only at
        // session termination. Mapping it to `session_end` (the old bug) made
        // `clear_current_session` delete the pointer after the first response,
        // so every subsequent turn silently dropped. `stop` is a SOFT
        // CHECKPOINT that accrues stats without clearing the pointer.
        ("Stop", "stop"),
    ]
}

/// Cursor v1 schema: lowerCamelCase event names, no matcher.
fn cursor_event_matrix() -> &'static [(&'static str, &'static str)] {
    &[
        ("sessionStart", "session_start"),
        ("postToolUse", "post_tool_use"),
        // Soft checkpoint (see claude_event_matrix) — not a session_end.
        ("stop", "stop"),
    ]
}

/// Hermes snake_case event names. The COMMAND for hermes is ALWAYS the bridge
/// script `~/.hermes/hooks/altevra-ingest.sh` — Hermes' own shell_hooks.py reads
/// `HOOK_EVENT_NAME` and the bridge maps to the correct Altevra event.
fn hermes_event_list() -> &'static [&'static str] {
    &[
        "pre_tool_call",
        "post_tool_call",
        "post_llm_call",
        "session_start",
        "session_end",
    ]
}

// ───────────────────────────────────────────────────────────────────────────
// Claude Code / Codex (shared JSON schema)
// ───────────────────────────────────────────────────────────────────────────

fn patch_claude_code(home: &Path, force: bool, dry_run: bool) -> Result<PatchOutcome> {
    let config = home.join(".claude/settings.json");
    patch_claude_style(config, "claude-code", force, dry_run)
}

fn patch_codex(home: &Path, force: bool, dry_run: bool) -> Result<PatchOutcome> {
    let config = home.join(".codex/hooks.json");
    patch_claude_style(config, "codex", force, dry_run)
}

fn patch_claude_style(
    config: PathBuf,
    tool: &str,
    force: bool,
    dry_run: bool,
) -> Result<PatchOutcome> {
    let mut outcome = PatchOutcome {
        tool: tool.to_string(),
        config_path: config.clone(),
        dry_run,
        ..Default::default()
    };

    if is_altevra_repo_target(&config) {
        outcome.self_skipped = true;
        return Ok(outcome);
    }

    // Backup BEFORE parsing — even a read could fail, but a corrupted file
    // shouldn't lose Pavle's data.
    if !dry_run {
        outcome.backup_path = backup_file(&config)?;
    }

    // Read existing config (or start from empty if first-time install).
    let mut root: Value = if config.exists() {
        let text = fs::read_to_string(&config)
            .with_context(|| format!("read {}", config.display()))?;
        serde_json::from_str(&text)
            .with_context(|| format!("parse {} as JSON", config.display()))?
    } else {
        Value::Object(Map::new())
    };

    let hooks = root
        .as_object_mut()
        .context("root is not a JSON object")?
        .entry("hooks")
        .or_insert_with(|| Value::Object(Map::new()))
        .as_object_mut()
        .context("hooks is not an object")?;

    for (event, altevra_arg) in claude_event_matrix() {
        let desired = claude_style_altevra_entry(tool, altevra_arg);
        let arr = hooks
            .entry((*event).to_string())
            .or_insert_with(|| Value::Array(Vec::new()))
            .as_array_mut()
            .with_context(|| format!("{event} entry is not an array"))?;
        match find_managed_index(arr) {
            Some(idx) => {
                if entries_equal_ignoring_marker(&arr[idx], &desired) {
                    outcome.skipped_events.push((*event).to_string());
                } else if force {
                    arr[idx] = desired;
                    outcome.added_events.push(format!("{event} (forced)"));
                } else {
                    outcome.drifted_events.push((*event).to_string());
                }
            }
            None => {
                arr.push(desired);
                outcome.added_events.push((*event).to_string());
            }
        }
        // Dedup: exactly ONE altevra entry per event. Legacy installs +
        // marker-blind re-installs leave variants behind, and each extra
        // double-fires the hook (double capture). Keep the canonical entry,
        // drop every other altevra-invoking entry; non-altevra entries
        // (imperium-emit etc.) are never touched — the additive contract
        // applies to foreign hooks, not our own duplicates.
        if !outcome.drifted_events.contains(&(*event).to_string()) {
            if let Some(keep) = find_managed_index(arr) {
                let mut i = arr.len();
                while i > 0 {
                    i -= 1;
                    if i != keep && entry_invokes_altevra_hook_handle(&arr[i]) {
                        arr.remove(i);
                        outcome
                            .added_events
                            .push(format!("{event} (deduped extra entry)"));
                    }
                }
            }
        }
    }

    if !outcome.drifted_events.is_empty() && !force {
        bail!(
            "[{}] drift detected on managed entries: {} — re-run with --force to overwrite",
            tool,
            outcome.drifted_events.join(", ")
        );
    }

    if dry_run {
        return Ok(outcome);
    }

    // Only write if we actually changed something.
    let nothing_changed = outcome.added_events.is_empty();
    if nothing_changed {
        return Ok(outcome);
    }
    write_json_pretty(&config, &root)?;
    // Post-write validation: re-parse; on failure restore.
    if let Err(e) = serde_json::from_str::<Value>(
        &fs::read_to_string(&config).unwrap_or_default(),
    ) {
        if let Some(b) = &outcome.backup_path {
            restore_from_backup(&config, b)?;
        }
        bail!("[{tool}] post-write JSON validation failed: {e} — restored from backup");
    }
    Ok(outcome)
}

/// Build the Claude/Codex hook entry we want to write for `event`. The entry
/// carries `_altevra_managed: true` so future runs recognise it.
///
/// P0 hardening (PLAN-ALIVE.md): bake the absolute `--db` path resolved on
/// the installing machine so a hook can never resolve a CWD-relative shadow
/// DB. Project/working_dir are derived inside hook-handle from
/// `$CLAUDE_PROJECT_DIR`/cwd — no `$ALTEVRA_PROJECT`.
fn claude_style_altevra_entry(_tool: &str, altevra_arg: &str) -> Value {
    let db = altevra_core::paths::default_db_path().display().to_string();
    json!({
        "matcher": "*",
        "_altevra_managed": true,
        "hooks": [{
            "type": "command",
            "command": format!("altevra hook-handle {altevra_arg} --tool {_tool} --db {db}"),
            "timeout": 5
        }]
    })
}

// ───────────────────────────────────────────────────────────────────────────
// Cursor (JSON v1 — no matcher, camelCase)
// ───────────────────────────────────────────────────────────────────────────

fn patch_cursor(home: &Path, force: bool, dry_run: bool) -> Result<PatchOutcome> {
    let config = home.join(".cursor/hooks.json");
    let mut outcome = PatchOutcome {
        tool: "cursor".to_string(),
        config_path: config.clone(),
        dry_run,
        ..Default::default()
    };

    if is_altevra_repo_target(&config) {
        outcome.self_skipped = true;
        return Ok(outcome);
    }

    if !dry_run {
        outcome.backup_path = backup_file(&config)?;
    }

    let mut root: Value = if config.exists() {
        let text = fs::read_to_string(&config)?;
        serde_json::from_str(&text)
            .with_context(|| format!("parse {} as JSON", config.display()))?
    } else {
        json!({"version": 1, "hooks": {}})
    };

    if root.get("version").is_none() {
        root.as_object_mut().unwrap().insert("version".into(), json!(1));
    }
    let hooks = root
        .as_object_mut()
        .context("root is not an object")?
        .entry("hooks")
        .or_insert_with(|| Value::Object(Map::new()))
        .as_object_mut()
        .context("hooks is not an object")?;

    for (event, altevra_arg) in cursor_event_matrix() {
        let desired = json!({
            "_altevra_managed": true,
            "command": format!("altevra hook-handle {altevra_arg} --tool cursor")
        });
        let arr = hooks
            .entry((*event).to_string())
            .or_insert_with(|| Value::Array(Vec::new()))
            .as_array_mut()
            .with_context(|| format!("cursor {event} entry is not an array"))?;
        match find_managed_index(arr) {
            Some(idx) => {
                if entries_equal_ignoring_marker(&arr[idx], &desired) {
                    outcome.skipped_events.push((*event).to_string());
                } else if force {
                    arr[idx] = desired;
                    outcome.added_events.push(format!("{event} (forced)"));
                } else {
                    outcome.drifted_events.push((*event).to_string());
                }
            }
            None => {
                arr.push(desired);
                outcome.added_events.push((*event).to_string());
            }
        }
    }

    if !outcome.drifted_events.is_empty() && !force {
        bail!(
            "[cursor] drift detected on managed entries: {} — re-run with --force",
            outcome.drifted_events.join(", ")
        );
    }

    if dry_run {
        return Ok(outcome);
    }
    if outcome.added_events.is_empty() {
        return Ok(outcome);
    }
    write_json_pretty(&config, &root)?;
    if let Err(e) = serde_json::from_str::<Value>(
        &fs::read_to_string(&config).unwrap_or_default(),
    ) {
        if let Some(b) = &outcome.backup_path {
            restore_from_backup(&config, b)?;
        }
        bail!("[cursor] post-write JSON validation failed: {e} — restored from backup");
    }
    Ok(outcome)
}

// ───────────────────────────────────────────────────────────────────────────
// Hermes (YAML — config + bridge script + chmod 0755)
// ───────────────────────────────────────────────────────────────────────────

fn patch_hermes(home: &Path, force: bool, dry_run: bool) -> Result<PatchOutcome> {
    let config = home.join(".hermes/config.yaml");
    let bridge_path = home.join(".hermes/hooks/altevra-ingest.sh");
    let mut outcome = PatchOutcome {
        tool: "hermes".to_string(),
        config_path: config.clone(),
        dry_run,
        ..Default::default()
    };

    if is_altevra_repo_target(&config) {
        outcome.self_skipped = true;
        return Ok(outcome);
    }

    if !dry_run {
        outcome.backup_path = backup_file(&config)?;
    }

    // 1) Install the bridge script (idempotent — overwrite is fine, content is
    //    fully managed by altevra-adapters::hermes_ingest_sh).
    if !dry_run {
        install_hermes_bridge(&bridge_path)?;
    }

    // 2) Patch the YAML hooks section.
    let mut root: serde_yaml::Value = if config.exists() {
        let text = fs::read_to_string(&config)?;
        serde_yaml::from_str(&text)
            .with_context(|| format!("parse {} as YAML", config.display()))?
    } else {
        serde_yaml::Value::Mapping(Default::default())
    };

    let root_map = root
        .as_mapping_mut()
        .context("hermes config root is not a mapping")?;

    let hooks_key = serde_yaml::Value::String("hooks".into());
    if !root_map.contains_key(&hooks_key) {
        root_map.insert(hooks_key.clone(), serde_yaml::Value::Mapping(Default::default()));
    }
    let hooks = root_map
        .get_mut(&hooks_key)
        .unwrap()
        .as_mapping_mut()
        .context("hermes hooks is not a mapping")?;

    let bridge_cmd = bridge_path.to_string_lossy().into_owned();
    let desired_entry = hermes_managed_entry(&bridge_cmd);

    for event in hermes_event_list() {
        let key = serde_yaml::Value::String((*event).into());
        if !hooks.contains_key(&key) {
            hooks.insert(key.clone(), serde_yaml::Value::Sequence(Vec::new()));
        }
        let arr = hooks
            .get_mut(&key)
            .unwrap()
            .as_sequence_mut()
            .with_context(|| format!("hermes hooks.{event} is not a sequence"))?;
        match find_managed_index_yaml(arr) {
            Some(idx) => {
                if yaml_entries_equal_ignoring_marker(&arr[idx], &desired_entry) {
                    outcome.skipped_events.push((*event).to_string());
                } else if force {
                    arr[idx] = desired_entry.clone();
                    outcome.added_events.push(format!("{event} (forced)"));
                } else {
                    outcome.drifted_events.push((*event).to_string());
                }
            }
            None => {
                arr.push(desired_entry.clone());
                outcome.added_events.push((*event).to_string());
            }
        }
    }

    if !outcome.drifted_events.is_empty() && !force {
        bail!(
            "[hermes] drift detected on managed entries: {} — re-run with --force",
            outcome.drifted_events.join(", ")
        );
    }

    if dry_run {
        return Ok(outcome);
    }
    if outcome.added_events.is_empty() {
        return Ok(outcome);
    }
    write_yaml(&config, &root)?;
    if let Err(e) = serde_yaml::from_str::<serde_yaml::Value>(
        &fs::read_to_string(&config).unwrap_or_default(),
    ) {
        if let Some(b) = &outcome.backup_path {
            restore_from_backup(&config, b)?;
        }
        bail!("[hermes] post-write YAML validation failed: {e} — restored from backup");
    }
    Ok(outcome)
}

/// Write the Hermes → Altevra bridge script and chmod 0755. Content is the
/// canonical text from `altevra-adapters::hermes_ingest_sh` so the script and
/// the in-process event mapping always agree.
fn install_hermes_bridge(path: &Path) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let body = altevra_adapters::hermes_ingest_sh::altevra_ingest_sh_content();
    fs::write(path, body)
        .with_context(|| format!("write bridge {}", path.display()))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(path)?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(path, perms)?;
    }
    Ok(())
}

fn hermes_managed_entry(bridge_cmd: &str) -> serde_yaml::Value {
    let mut m = serde_yaml::Mapping::new();
    m.insert(
        serde_yaml::Value::String("command".into()),
        serde_yaml::Value::String(bridge_cmd.into()),
    );
    m.insert(
        serde_yaml::Value::String("timeout".into()),
        serde_yaml::Value::Number(serde_yaml::Number::from(5_i64)),
    );
    // Hermes shell_hooks.py uses raw.get("command") / raw.get("timeout") — extra
    // keys are silently ignored, so this marker is safe and survives YAML
    // round-trips (unlike `# altevra-managed` comments which serde_yaml strips).
    m.insert(
        serde_yaml::Value::String("altevra_managed".into()),
        serde_yaml::Value::Bool(true),
    );
    serde_yaml::Value::Mapping(m)
}

// ───────────────────────────────────────────────────────────────────────────
// Marker / drift helpers (JSON + YAML)
// ───────────────────────────────────────────────────────────────────────────

fn find_managed_index(arr: &[Value]) -> Option<usize> {
    // Primary identification: the explicit marker. Fallback: any entry whose
    // command invokes `altevra hook-handle` is ours regardless of marker —
    // legacy installs (adapter `connect` template, pre-marker versions) wrote
    // unmarked entries; without this fallback a re-install APPENDS a duplicate
    // and every hook event fires twice (double capture).
    arr.iter()
        .position(|v| {
            v.get(MANAGED_MARKER)
                .and_then(Value::as_bool)
                .unwrap_or(false)
        })
        .or_else(|| arr.iter().position(entry_invokes_altevra_hook_handle))
}

/// True when any nested hook command in this entry calls `altevra hook-handle`.
fn entry_invokes_altevra_hook_handle(entry: &Value) -> bool {
    entry
        .get("hooks")
        .and_then(Value::as_array)
        .map(|hooks| {
            hooks.iter().any(|h| {
                h.get("command")
                    .and_then(Value::as_str)
                    .is_some_and(|c| c.contains("altevra hook-handle"))
            })
        })
        .unwrap_or(false)
}

fn find_managed_index_yaml(arr: &[serde_yaml::Value]) -> Option<usize> {
    arr.iter().position(|v| {
        v.as_mapping()
            .and_then(|m| m.get(serde_yaml::Value::String("altevra_managed".into())))
            .and_then(serde_yaml::Value::as_bool)
            .unwrap_or(false)
    })
}

/// Two entries are "equal" if they match after stripping the marker key. This
/// is how we detect a managed entry that hasn't drifted (idempotent re-run).
fn entries_equal_ignoring_marker(a: &Value, b: &Value) -> bool {
    let mut a = a.clone();
    let mut b = b.clone();
    if let Some(o) = a.as_object_mut() {
        o.remove(MANAGED_MARKER);
    }
    if let Some(o) = b.as_object_mut() {
        o.remove(MANAGED_MARKER);
    }
    a == b
}

fn yaml_entries_equal_ignoring_marker(a: &serde_yaml::Value, b: &serde_yaml::Value) -> bool {
    let strip = |v: &serde_yaml::Value| -> serde_yaml::Value {
        let mut c = v.clone();
        if let Some(m) = c.as_mapping_mut() {
            m.remove(serde_yaml::Value::String("altevra_managed".into()));
        }
        c
    };
    strip(a) == strip(b)
}

// ───────────────────────────────────────────────────────────────────────────
// File writers
// ───────────────────────────────────────────────────────────────────────────

fn write_json_pretty(path: &Path, root: &Value) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let pretty = serde_json::to_string_pretty(root)?;
    fs::write(path, pretty)
        .with_context(|| format!("write {}", path.display()))?;
    Ok(())
}

fn write_yaml(path: &Path, root: &serde_yaml::Value) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let text = serde_yaml::to_string(root)?;
    fs::write(path, text)
        .with_context(|| format!("write {}", path.display()))?;
    Ok(())
}

// ───────────────────────────────────────────────────────────────────────────
// Self-skip — never wire Altevra into Altevra's own dev tree (SI-6)
// ───────────────────────────────────────────────────────────────────────────

/// True if the target config path lives inside the Altevra workspace. Used by
/// the per-target self-skip (e.g. when smart-scope would patch the repo's own
/// `.claude/settings.json`). The global-gate in `run()` handles the case where
/// the *cwd* is inside the repo but the *target* is outside it.
fn is_altevra_repo_target(target: &Path) -> bool {
    // Walk up from the target itself, since the target is the path we'd write.
    if let Some(root) = find_altevra_workspace_from(target) {
        if target.starts_with(&root) {
            return true;
        }
    }
    // Belt-and-braces: also catch the case where cwd is in the altevra repo
    // and the target sits within it (preserves prior behaviour for the
    // existing `install_hooks_self_skip_altevra_repo` test where the target
    // is inside cwd).
    if let Ok(cwd) = std::env::current_dir() {
        if let Some(root) = find_altevra_workspace_from(&cwd) {
            if target.starts_with(&root) {
                return true;
            }
        }
    }
    false
}

/// Walk up from `current_dir()` looking for the Altevra workspace root.
/// Returns the deepest matching Cargo.toml directory, or None if cwd is not
/// inside Altevra.
fn detect_altevra_workspace_from_cwd() -> Option<PathBuf> {
    let cwd = std::env::current_dir().ok()?;
    find_altevra_workspace_from(&cwd)
}

/// Walk up from `start` looking for a `Cargo.toml` that identifies as the
/// Altevra workspace (real package name match — NOT a raw substring scan).
/// Returns the directory containing that Cargo.toml.
fn find_altevra_workspace_from(start: &Path) -> Option<PathBuf> {
    let mut probe = start;
    loop {
        let cargo = probe.join("Cargo.toml");
        if cargo.exists() {
            if let Ok(text) = fs::read_to_string(&cargo) {
                if cargo_toml_is_altevra_workspace(&text) {
                    return Some(probe.to_path_buf());
                }
            }
        }
        match probe.parent() {
            Some(p) if p != probe => probe = p,
            _ => return None,
        }
    }
}

/// Decide whether a `Cargo.toml`'s content identifies it as an Altevra
/// workspace/crate. Uses a real TOML parse — a downstream Cargo.toml that
/// merely lists `altevra = "1.0"` as a dependency must NOT trigger self-skip.
///
/// Match criteria (any one is sufficient):
/// 1. `[package].name` equals `altevra` or starts with `altevra-`.
/// 2. `[workspace].members` contains any entry whose path segment starts
///    with `altevra-` or equals `altevra`/`crates/altevra` (covers the
///    workspace-root case where there is no `[package]`).
fn cargo_toml_is_altevra_workspace(text: &str) -> bool {
    let Ok(value) = toml::from_str::<toml::Value>(text) else {
        return false;
    };

    if let Some(name) = value
        .get("package")
        .and_then(|p| p.get("name"))
        .and_then(toml::Value::as_str)
    {
        if name == "altevra" || name.starts_with("altevra-") {
            return true;
        }
    }

    if let Some(members) = value
        .get("workspace")
        .and_then(|w| w.get("members"))
        .and_then(toml::Value::as_array)
    {
        for m in members {
            if let Some(s) = m.as_str() {
                let last = s.rsplit('/').next().unwrap_or(s);
                if last == "altevra" || last.starts_with("altevra-") {
                    return true;
                }
            }
        }
    }

    false
}

/// Append a JSON-ish line to `~/.altevra/install-hooks-decisions.log` recording
/// the global self-skip outcome. We use the same log file that smart-scope
/// writes to so a single forensic record covers every refusal.
fn log_self_skip_decision(home: &Path, repo_root: &Path, cwd: Option<&Path>, bypassed: bool) {
    let log_dir = home.join(".altevra");
    if let Err(_e) = fs::create_dir_all(&log_dir) {
        return;
    }
    let ts = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    let action = if bypassed { "ALLOW-BYPASS" } else { "DENY" };
    let line = format!(
        "{ts}\tSELF-SKIP-GLOBAL\trepo={}\tcwd={}\taction={action}\tenv={SELF_SKIP_BYPASS_ENV}={}\n",
        repo_root.display(),
        cwd.map(|p| p.display().to_string()).unwrap_or_default(),
        if bypassed { "1" } else { "unset" }
    );
    let log_path = log_dir.join("install-hooks-decisions.log");
    let mut prior = fs::read_to_string(&log_path).unwrap_or_default();
    if !prior.is_empty() && !prior.ends_with('\n') {
        prior.push('\n');
    }
    prior.push_str(&line);
    let _ = fs::write(&log_path, prior);
}

// ───────────────────────────────────────────────────────────────────────────
// Smart auto-scope detection
// ───────────────────────────────────────────────────────────────────────────

#[derive(Debug, Clone)]
pub struct ScopeDecision {
    pub path: PathBuf,
    pub score: u8,
    pub action: String,
}

/// Walk projects + projects.yaml and decide per repo whether to also patch a
/// project-local `.claude/settings.json`. Decisions are logged to
/// `~/.altevra/install-hooks-decisions.log`. Score:
///   +1 has AGENTS.md or CLAUDE.md
///   +1 already has `.claude/settings.json` with non-altevra hooks
///   +1 listed in projects.yaml with a default_agent
///   +1 P0 or P1 priority in projects.yaml
/// Threshold: score >= 3 → patch.
pub fn smart_scope_apply(home: &Path, projects_root: &Path) -> Result<Vec<ScopeDecision>> {
    let log_dir = home.join(".altevra");
    fs::create_dir_all(&log_dir)?;
    let log_path = log_dir.join("install-hooks-decisions.log");

    let yaml_meta = load_projects_yaml(&home.join(".imperium/identity/projects.yaml"));
    let repos = walk_for_git_repos(projects_root);
    let mut decisions = Vec::new();
    let mut log_lines = Vec::new();
    let ts = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);

    for repo in repos {
        if repo.join(".altevra-skip").exists() {
            log_lines.push(format!(
                "{ts}\t{}\tSKIP\treason=altevra-skip-marker",
                repo.display()
            ));
            continue;
        }
        if is_altevra_repo_target(&repo) || repo_is_altevra(&repo) {
            log_lines.push(format!(
                "{ts}\t{}\tSKIP\treason=altevra-self",
                repo.display()
            ));
            continue;
        }
        let score = score_repo(&repo, &yaml_meta);
        let action = if score >= 3 {
            match write_project_claude_settings(&repo) {
                Ok(b) => {
                    if b {
                        "WROTE-PROJECT-CONFIG".to_string()
                    } else {
                        "SKIP-ALREADY-MANAGED".to_string()
                    }
                }
                Err(e) => format!("ERROR:{e}"),
            }
        } else {
            "SKIP-LOW-SCORE".to_string()
        };
        log_lines.push(format!(
            "{ts}\t{}\tscore={score}\taction={action}",
            repo.display()
        ));
        decisions.push(ScopeDecision {
            path: repo,
            score,
            action,
        });
    }

    // Append decisions log (never truncate — this is forensic history).
    let mut prior = fs::read_to_string(&log_path).unwrap_or_default();
    if !prior.is_empty() && !prior.ends_with('\n') {
        prior.push('\n');
    }
    prior.push_str(&log_lines.join("\n"));
    prior.push('\n');
    fs::write(&log_path, prior)?;

    Ok(decisions)
}

fn repo_is_altevra(repo: &Path) -> bool {
    let cargo = repo.join("Cargo.toml");
    if !cargo.exists() {
        return false;
    }
    fs::read_to_string(&cargo)
        .map(|t| cargo_toml_is_altevra_workspace(&t))
        .unwrap_or(false)
}

/// Walk `root` shallowly looking for git repos (1-2 levels deep — Pavle's
/// projects are categorized like `ai-tooling/altevra`, `biznis/revesta`).
fn walk_for_git_repos(root: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let Ok(top) = fs::read_dir(root) else {
        return out;
    };
    for entry in top.flatten() {
        let p = entry.path();
        if !p.is_dir() {
            continue;
        }
        if p.join(".git").exists() {
            out.push(p);
            continue;
        }
        if let Ok(inner) = fs::read_dir(&p) {
            for inner_entry in inner.flatten() {
                let q = inner_entry.path();
                if q.is_dir() && q.join(".git").exists() {
                    out.push(q);
                }
            }
        }
    }
    out
}

/// Minimal extract from projects.yaml: per-path → (default_agent_known, priority).
#[derive(Default)]
struct ProjectsMeta {
    by_path: std::collections::HashMap<PathBuf, (bool, String)>,
    paths: BTreeSet<PathBuf>,
}

fn load_projects_yaml(path: &Path) -> ProjectsMeta {
    let mut meta = ProjectsMeta::default();
    let Ok(text) = fs::read_to_string(path) else {
        return meta;
    };
    let Ok(root) = serde_yaml::from_str::<serde_yaml::Value>(&text) else {
        return meta;
    };
    let Some(projects) = root.get("projects").and_then(serde_yaml::Value::as_sequence) else {
        return meta;
    };
    for p in projects {
        let path_str = p.get("path").and_then(serde_yaml::Value::as_str);
        let agent = p.get("default_agent").and_then(serde_yaml::Value::as_str);
        let priority = p
            .get("priority")
            .and_then(serde_yaml::Value::as_str)
            .unwrap_or("")
            .to_string();
        if let Some(s) = path_str {
            let pb = PathBuf::from(s);
            meta.by_path.insert(pb.clone(), (agent.is_some(), priority));
            meta.paths.insert(pb);
        }
    }
    meta
}

fn score_repo(repo: &Path, yaml: &ProjectsMeta) -> u8 {
    let mut score = 0u8;
    if repo.join("AGENTS.md").exists() || repo.join("CLAUDE.md").exists() {
        score += 1;
    }
    let claude_settings = repo.join(".claude/settings.json");
    if claude_settings.exists() {
        if let Ok(text) = fs::read_to_string(&claude_settings) {
            if !text.contains(MANAGED_MARKER) && text.contains("\"hooks\"") {
                score += 1;
            }
        }
    }
    if let Some((agent_set, priority)) = yaml.by_path.get(repo) {
        if *agent_set {
            score += 1;
        }
        if priority == "P0" || priority == "P1" {
            score += 1;
        }
    }
    score
}

/// Write project-local `.claude/settings.json` with the same hook matrix. Same
/// idempotency rules apply. Returns Ok(true) if something was added.
fn write_project_claude_settings(repo: &Path) -> Result<bool> {
    let config = repo.join(".claude/settings.json");
    if !dir_writable(&config) {
        return Ok(false);
    }
    let outcome = patch_claude_style(config, "claude-code", false, false)?;
    Ok(!outcome.added_events.is_empty())
}

fn dir_writable(file: &Path) -> bool {
    let Some(dir) = file.parent() else {
        return false;
    };
    fs::create_dir_all(dir).is_ok()
}

// ───────────────────────────────────────────────────────────────────────────
// Tests — fixture configs ONLY; NEVER touch real ~/.<tool>/* files
// ───────────────────────────────────────────────────────────────────────────

#[cfg(test)]
// `cwd_lock()` returns a `std::sync::MutexGuard` that intentionally lives
// across `run(args).await` to serialize cwd + env var manipulation. This is
// safe here because each `#[tokio::test]` builds its own current-thread
// runtime, so the guard never travels between threads.
#[allow(clippy::await_holding_lock)]
mod tests {
    use super::*;
    use serde_json::json;
    use std::sync::{Mutex, MutexGuard, OnceLock};
    use tempfile::TempDir;

    /// Mutex guarding tests that touch process-global state (cwd or the
    /// SELF_SKIP_BYPASS_ENV var). Without it, parallel test runs race on
    /// `set_current_dir` and see another test's fake altevra workspace.
    fn cwd_lock() -> MutexGuard<'static, ()> {
        static LOCK: OnceLock<Mutex<()>> = OnceLock::new();
        LOCK.get_or_init(|| Mutex::new(()))
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner())
    }

    /// Seed the existing imperium-emit entry so we can assert we preserved it.
    fn seed_claude_settings(home: &Path) -> PathBuf {
        let path = home.join(".claude/settings.json");
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        let existing = json!({
            "hooks": {
                "SessionStart": [{
                    "matcher": "",
                    "hooks": [{
                        "type": "command",
                        "command": "bash ~/.claude/hooks/imperium-emit.sh session-start",
                        "timeout": 2
                    }]
                }]
            }
        });
        fs::write(&path, serde_json::to_string_pretty(&existing).unwrap()).unwrap();
        path
    }

    #[tokio::test]
    async fn install_hooks_claude_code_additive() {
        let _guard = cwd_lock();
        let tmp = TempDir::new().unwrap();
        seed_claude_settings(tmp.path());

        let args = InstallHooksArgs {
            tool: Some("claude-code".into()),
            force: false,
            dry_run: false,
            home: Some(tmp.path().to_path_buf()),
            projects_root: None,
            // `cargo test` runs from the altevra workspace dir, which would
            // trip the SI-6 global gate. Bypass it for fixture-only tests.
            bypass_self_skip: true,
        };
        run(args).await.unwrap();

        let text = fs::read_to_string(tmp.path().join(".claude/settings.json")).unwrap();
        let root: Value = serde_json::from_str(&text).unwrap();
        let session_start = &root["hooks"]["SessionStart"];
        // imperium-emit MUST still be there.
        let imp_kept = session_start
            .as_array()
            .unwrap()
            .iter()
            .any(|e| e.to_string().contains("imperium-emit"));
        assert!(imp_kept, "imperium-emit entry was removed");
        // altevra entry was added with marker.
        let altevra_added = session_start
            .as_array()
            .unwrap()
            .iter()
            .any(|e| e.get(MANAGED_MARKER).is_some());
        assert!(altevra_added, "altevra entry missing");
        // All 5 events present.
        for (event, _) in claude_event_matrix() {
            assert!(root["hooks"].get(event).is_some(), "missing event {event}");
        }
    }

    #[tokio::test]
    async fn install_hooks_idempotent() {
        let _guard = cwd_lock();
        let tmp = TempDir::new().unwrap();
        seed_claude_settings(tmp.path());

        let args = InstallHooksArgs {
            tool: Some("claude-code".into()),
            force: false,
            dry_run: false,
            home: Some(tmp.path().to_path_buf()),
            projects_root: None,
            bypass_self_skip: true,
        };
        run(args.clone()).await.unwrap();
        // Capture entry count after first run.
        let text1 = fs::read_to_string(tmp.path().join(".claude/settings.json")).unwrap();
        let root1: Value = serde_json::from_str(&text1).unwrap();
        let count1 = root1["hooks"]["SessionStart"].as_array().unwrap().len();

        // Re-run — count must not change.
        run(args).await.unwrap();
        let text2 = fs::read_to_string(tmp.path().join(".claude/settings.json")).unwrap();
        let root2: Value = serde_json::from_str(&text2).unwrap();
        let count2 = root2["hooks"]["SessionStart"].as_array().unwrap().len();
        assert_eq!(count1, count2, "idempotent re-run added duplicates");
    }

    #[tokio::test]
    async fn install_hooks_drift_requires_force() {
        let _guard = cwd_lock();
        let tmp = TempDir::new().unwrap();
        seed_claude_settings(tmp.path());

        let args = InstallHooksArgs {
            tool: Some("claude-code".into()),
            force: false,
            dry_run: false,
            home: Some(tmp.path().to_path_buf()),
            projects_root: None,
            bypass_self_skip: true,
        };
        run(args.clone()).await.unwrap();

        // Hand-edit the managed entry's command (simulate drift).
        let path = tmp.path().join(".claude/settings.json");
        let mut root: Value = serde_json::from_str(&fs::read_to_string(&path).unwrap()).unwrap();
        let arr = root["hooks"]["SessionStart"].as_array_mut().unwrap();
        for entry in arr.iter_mut() {
            if entry.get(MANAGED_MARKER).is_some() {
                entry["hooks"][0]["command"] = json!("tampered-command");
            }
        }
        fs::write(&path, serde_json::to_string_pretty(&root).unwrap()).unwrap();

        // Re-run without --force must error.
        let err = run(args.clone()).await.err();
        assert!(err.is_some(), "drift must abort without --force");
        assert!(
            format!("{err:?}").contains("drift"),
            "error must mention drift, got: {err:?}"
        );

        // With --force it succeeds.
        let forced = InstallHooksArgs { force: true, ..args };
        run(forced).await.unwrap();
        let root: Value = serde_json::from_str(&fs::read_to_string(&path).unwrap()).unwrap();
        let cmd = root["hooks"]["SessionStart"]
            .as_array()
            .unwrap()
            .iter()
            .find(|e| e.get(MANAGED_MARKER).is_some())
            .unwrap()["hooks"][0]["command"]
            .as_str()
            .unwrap()
            .to_string();
        assert!(
            cmd.starts_with("altevra hook-handle"),
            "forced overwrite did not restore canonical command: {cmd}"
        );
    }

    #[tokio::test]
    async fn install_hooks_smart_scope_decides_per_project() {
        let _guard = cwd_lock();
        let tmp = TempDir::new().unwrap();
        let home = tmp.path();
        let projects = home.join("projekti");
        fs::create_dir_all(&projects).unwrap();

        // Repo A: score >= 3 (CLAUDE.md + existing non-altevra hooks + yaml entry P0).
        let a = projects.join("ai-tooling/high-score");
        fs::create_dir_all(a.join(".git")).unwrap();
        fs::write(a.join("CLAUDE.md"), "x").unwrap();
        fs::create_dir_all(a.join(".claude")).unwrap();
        fs::write(
            a.join(".claude/settings.json"),
            r#"{"hooks":{"SessionStart":[{"matcher":"","hooks":[{"type":"command","command":"echo hi"}]}]}}"#,
        )
        .unwrap();

        // Repo B: bare (score 0).
        let b = projects.join("ai-tooling/bare");
        fs::create_dir_all(b.join(".git")).unwrap();

        // Repo C: has .altevra-skip marker.
        let c = projects.join("ai-tooling/skip-me");
        fs::create_dir_all(c.join(".git")).unwrap();
        fs::write(c.join(".altevra-skip"), "").unwrap();

        // Seed minimal projects.yaml referencing repo A as P0 with default_agent.
        let yaml_path = home.join(".imperium/identity/projects.yaml");
        fs::create_dir_all(yaml_path.parent().unwrap()).unwrap();
        let yaml = format!(
            "version: 1\nprojects:\n  - id: high-score\n    path: \"{}\"\n    default_agent: claude\n    priority: P0\n",
            a.display()
        );
        fs::write(&yaml_path, yaml).unwrap();

        let decisions = smart_scope_apply(home, &projects).unwrap();
        let a_decision = decisions
            .iter()
            .find(|d| d.path == a)
            .expect("repo A missing from decisions");
        assert!(a_decision.score >= 3, "repo A score < 3: {a_decision:?}");
        assert!(
            a_decision.action.contains("WROTE") || a_decision.action.contains("SKIP-ALREADY-MANAGED"),
            "expected write for high-score repo, got {}",
            a_decision.action
        );
        // Bare repo gets skipped or low-score.
        if let Some(b_decision) = decisions.iter().find(|d| d.path == b) {
            assert!(b_decision.score < 3);
            assert_eq!(b_decision.action, "SKIP-LOW-SCORE");
        }
        // Skip-marker repo never appears in decisions.
        assert!(
            decisions.iter().all(|d| d.path != c),
            "repo with .altevra-skip should be omitted"
        );

        // Decisions log exists and references at least one repo.
        let log = fs::read_to_string(home.join(".altevra/install-hooks-decisions.log")).unwrap();
        assert!(log.contains("high-score"));
        assert!(log.contains("skip-me\tSKIP"));
    }

    #[tokio::test]
    async fn install_hooks_backup_always_written() {
        let _guard = cwd_lock();
        let tmp = TempDir::new().unwrap();
        let path = seed_claude_settings(tmp.path());

        let args = InstallHooksArgs {
            tool: Some("claude-code".into()),
            force: false,
            dry_run: false,
            home: Some(tmp.path().to_path_buf()),
            projects_root: None,
            bypass_self_skip: true,
        };
        run(args).await.unwrap();

        // A sibling file matching <name>.altevra-backup-<ts> must exist.
        let parent = path.parent().unwrap();
        let backups: Vec<_> = fs::read_dir(parent)
            .unwrap()
            .flatten()
            .filter(|e| {
                let name = e.file_name().to_string_lossy().into_owned();
                name.contains("altevra-backup-")
            })
            .collect();
        assert!(!backups.is_empty(), "no backup file written");
        let name = backups[0].file_name().to_string_lossy().into_owned();
        assert!(
            name.contains(".altevra-backup-"),
            "backup name shape wrong: {name}"
        );
    }

    #[tokio::test]
    async fn install_hooks_self_skip_altevra_repo() {
        let _guard = cwd_lock();
        // Build a fake "altevra repo" tree with a Cargo.toml whose
        // [package].name starts with `altevra-`, and aim the install at a
        // settings.json INSIDE that tree. The global gate must bail() and
        // nothing must be written.
        let tmp = TempDir::new().unwrap();
        let fake_repo = tmp.path().join("fake-altevra");
        fs::create_dir_all(&fake_repo).unwrap();
        fs::write(fake_repo.join("Cargo.toml"), "[package]\nname = \"altevra-fake\"\n").unwrap();
        // Pretend HOME is INSIDE the repo so the target config sits under it.
        let home_inside = fake_repo.join("home");
        fs::create_dir_all(&home_inside).unwrap();

        let prev = std::env::current_dir().unwrap();
        std::env::set_current_dir(&fake_repo).unwrap();
        // Ensure bypass is OFF for this test.
        std::env::remove_var(SELF_SKIP_BYPASS_ENV);

        let args = InstallHooksArgs {
            tool: Some("claude-code".into()),
            force: false,
            dry_run: false,
            home: Some(home_inside.clone()),
            projects_root: None,
            bypass_self_skip: false,
        };
        let res = run(args).await;
        std::env::set_current_dir(prev).unwrap();
        let err = res.expect_err("global self-skip gate did not refuse");
        let msg = format!("{err}");
        assert!(
            msg.contains("refuses to run from inside the altevra repo"),
            "bail message wrong: {msg}"
        );
        assert!(msg.contains(SELF_SKIP_BYPASS_ENV), "missing bypass hint: {msg}");

        // No file should have been created.
        assert!(
            !home_inside.join(".claude/settings.json").exists(),
            "self-skip violated: claude settings.json was written under altevra repo"
        );
    }

    #[tokio::test]
    async fn install_hooks_global_refuses_from_altevra_repo_cwd() {
        let _guard = cwd_lock();
        // The dangerous real-world scenario: cwd is inside the Altevra repo
        // but the target is $HOME/.claude/settings.json which is OUTSIDE the
        // repo. The pre-fix code returned Ok with self_skipped=false and
        // happily patched the global config. The new global gate must bail.
        let tmp = TempDir::new().unwrap();
        let fake_repo = tmp.path().join("altevra-workspace");
        fs::create_dir_all(fake_repo.join("crates/altevra-cli")).unwrap();
        fs::write(
            fake_repo.join("Cargo.toml"),
            "[workspace]\nmembers = [\"crates/altevra-cli\", \"crates/altevra-core\"]\n",
        )
        .unwrap();

        // HOME lives in a sibling dir — fully outside the repo.
        let home_outside = tmp.path().join("user-home");
        fs::create_dir_all(&home_outside).unwrap();
        // Pre-create a settings.json so we can prove it was NOT mutated.
        let target = home_outside.join(".claude/settings.json");
        fs::create_dir_all(target.parent().unwrap()).unwrap();
        let original = r#"{"hooks": {"SessionStart": []}}"#;
        fs::write(&target, original).unwrap();

        let prev = std::env::current_dir().unwrap();
        std::env::set_current_dir(&fake_repo).unwrap();
        std::env::remove_var(SELF_SKIP_BYPASS_ENV);

        let args = InstallHooksArgs {
            tool: Some("claude-code".into()),
            force: false,
            dry_run: false,
            home: Some(home_outside.clone()),
            projects_root: None,
            bypass_self_skip: false,
        };
        let res = run(args).await;
        std::env::set_current_dir(prev).unwrap();
        let err = res.expect_err("global gate did not refuse with cwd inside altevra");
        let msg = format!("{err}");
        assert!(msg.contains("SI-6") || msg.contains("self-write"), "msg: {msg}");

        // Pre-existing settings.json must be untouched (byte-identical).
        let after = fs::read_to_string(&target).unwrap();
        assert_eq!(after, original, "global config was mutated despite refusal");

        // Decisions log records a DENY line for the global self-skip.
        let log_path = home_outside.join(".altevra/install-hooks-decisions.log");
        assert!(log_path.exists(), "decisions log not written");
        let log = fs::read_to_string(&log_path).unwrap();
        assert!(log.contains("SELF-SKIP-GLOBAL"), "log line missing tag: {log}");
        assert!(log.contains("action=DENY"), "log line missing action=DENY: {log}");
        assert!(
            log.contains("env=ALTEVRA_BYPASS_SELF_SKIP=unset"),
            "log line missing env marker: {log}"
        );
    }

    #[tokio::test]
    async fn install_hooks_self_skip_bypass_env_allows() {
        let _guard = cwd_lock();
        // Same setup as `install_hooks_global_refuses_from_altevra_repo_cwd`
        // but with ALTEVRA_BYPASS_SELF_SKIP=1 — the gate logs ALLOW-BYPASS
        // and proceeds with the install.
        let tmp = TempDir::new().unwrap();
        let fake_repo = tmp.path().join("altevra-workspace");
        fs::create_dir_all(fake_repo.join("crates/altevra-cli")).unwrap();
        fs::write(
            fake_repo.join("Cargo.toml"),
            "[workspace]\nmembers = [\"crates/altevra-cli\"]\n",
        )
        .unwrap();
        let home_outside = tmp.path().join("user-home");
        fs::create_dir_all(&home_outside).unwrap();

        let prev = std::env::current_dir().unwrap();
        std::env::set_current_dir(&fake_repo).unwrap();
        std::env::set_var(SELF_SKIP_BYPASS_ENV, "1");

        let args = InstallHooksArgs {
            tool: Some("claude-code".into()),
            force: false,
            dry_run: false,
            home: Some(home_outside.clone()),
            projects_root: None,
            // Intentionally false — we want to confirm the *env* var alone
            // bypasses the gate.
            bypass_self_skip: false,
        };
        let res = run(args).await;
        // Always clean up the env + cwd, even on failure.
        std::env::set_current_dir(prev).unwrap();
        std::env::remove_var(SELF_SKIP_BYPASS_ENV);
        res.expect("bypass env should allow the install to proceed");

        // Settings file was created (gate did not bail).
        assert!(
            home_outside.join(".claude/settings.json").exists(),
            "bypass env failed: settings.json was not written"
        );
        // Log records the bypass.
        let log = fs::read_to_string(home_outside.join(".altevra/install-hooks-decisions.log"))
            .unwrap();
        assert!(log.contains("action=ALLOW-BYPASS"), "log missing bypass: {log}");
    }

    #[tokio::test]
    async fn install_hooks_downstream_cargo_dep_does_not_self_skip() {
        let _guard = cwd_lock();
        // Pavle ships a downstream project that lists altevra as a *dependency*.
        // Running `altevra install-hooks` from that project's cwd MUST NOT
        // refuse — only matching the altevra workspace/crate by package name
        // counts.
        let tmp = TempDir::new().unwrap();
        let downstream = tmp.path().join("downstream-app");
        fs::create_dir_all(&downstream).unwrap();
        fs::write(
            downstream.join("Cargo.toml"),
            "[package]\nname = \"downstream-app\"\nversion = \"0.1.0\"\n\
             [dependencies]\naltevra = \"1.0\"\nserde = \"1\"\n",
        )
        .unwrap();
        let home_outside = tmp.path().join("user-home");
        fs::create_dir_all(&home_outside).unwrap();

        let prev = std::env::current_dir().unwrap();
        std::env::set_current_dir(&downstream).unwrap();
        std::env::remove_var(SELF_SKIP_BYPASS_ENV);

        let args = InstallHooksArgs {
            tool: Some("claude-code".into()),
            force: false,
            dry_run: false,
            home: Some(home_outside.clone()),
            projects_root: None,
            bypass_self_skip: false,
        };
        let res = run(args).await;
        std::env::set_current_dir(prev).unwrap();
        res.expect("downstream Cargo.toml with altevra dep must not trigger self-skip");

        // And we DID write the settings.json (proof the gate didn't fire).
        assert!(home_outside.join(".claude/settings.json").exists());
    }

    #[test]
    fn cargo_toml_detects_real_altevra_workspace() {
        // Package-name match.
        assert!(cargo_toml_is_altevra_workspace(
            "[package]\nname = \"altevra-cli\"\nversion = \"0.1\"\n"
        ));
        assert!(cargo_toml_is_altevra_workspace(
            "[package]\nname = \"altevra\"\nversion = \"0.1\"\n"
        ));
        // Workspace-members match (the real altevra root Cargo.toml shape).
        assert!(cargo_toml_is_altevra_workspace(
            "[workspace]\nmembers = [\"crates/altevra-core\", \"crates/altevra-cli\"]\n"
        ));
    }

    #[test]
    fn cargo_toml_rejects_downstream_with_altevra_dep() {
        // The whole point of the tighter check: a downstream Cargo.toml that
        // merely depends on altevra must NOT be classified as altevra itself.
        assert!(!cargo_toml_is_altevra_workspace(
            "[package]\nname = \"customer-app\"\nversion = \"0.1\"\n\
             [dependencies]\naltevra = \"1.0\"\n"
        ));
        // Also reject names that *contain* altevra but don't start with it.
        assert!(!cargo_toml_is_altevra_workspace(
            "[package]\nname = \"some-altevra-thing\"\nversion = \"0.1\"\n"
        ));
        // Unrelated workspace with no altevra members.
        assert!(!cargo_toml_is_altevra_workspace(
            "[workspace]\nmembers = [\"crates/foo\", \"crates/bar\"]\n"
        ));
    }

    #[tokio::test]
    async fn install_hooks_cursor_v1_schema() {
        let _guard = cwd_lock();
        let tmp = TempDir::new().unwrap();
        let args = InstallHooksArgs {
            tool: Some("cursor".into()),
            force: false,
            dry_run: false,
            home: Some(tmp.path().to_path_buf()),
            projects_root: None,
            bypass_self_skip: true,
        };
        run(args).await.unwrap();
        let text = fs::read_to_string(tmp.path().join(".cursor/hooks.json")).unwrap();
        let root: Value = serde_json::from_str(&text).unwrap();
        assert_eq!(root["version"], json!(1));
        // Cursor entries have no "matcher" (v1 schema) and a flat "command".
        for (event, _) in cursor_event_matrix() {
            let arr = root["hooks"][event].as_array().unwrap();
            let altevra = arr
                .iter()
                .find(|e| e.get(MANAGED_MARKER).is_some())
                .expect("altevra entry missing");
            assert!(altevra.get("matcher").is_none(), "cursor v1 has no matcher");
            assert!(altevra["command"].as_str().unwrap().starts_with("altevra hook-handle"));
        }
    }

    #[tokio::test]
    async fn install_hooks_hermes_writes_bridge_script() {
        let _guard = cwd_lock();
        let tmp = TempDir::new().unwrap();
        // Seed a minimal hermes config with an existing imperium-emit hook to
        // confirm we preserve it.
        let cfg = tmp.path().join(".hermes/config.yaml");
        fs::create_dir_all(cfg.parent().unwrap()).unwrap();
        fs::write(
            &cfg,
            "model:\n  default: gpt-5.5\nhooks:\n  pre_tool_call:\n  - command: ~/.hermes/hooks/imperium-emit.sh\n    timeout: 2\n",
        )
        .unwrap();

        let args = InstallHooksArgs {
            tool: Some("hermes".into()),
            force: false,
            dry_run: false,
            home: Some(tmp.path().to_path_buf()),
            projects_root: None,
            bypass_self_skip: true,
        };
        run(args).await.unwrap();

        // Bridge script must exist + be executable.
        let bridge = tmp.path().join(".hermes/hooks/altevra-ingest.sh");
        assert!(bridge.exists());
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = fs::metadata(&bridge).unwrap().permissions().mode() & 0o777;
            assert_eq!(mode, 0o755);
        }

        // YAML: imperium-emit preserved, altevra entry added with marker.
        let text = fs::read_to_string(&cfg).unwrap();
        assert!(text.contains("imperium-emit"));
        assert!(text.contains("altevra-ingest.sh"));
        assert!(text.contains("altevra_managed"));
    }
}
