//! Cursor adapter — Cursor IDE integration.
//!
//! Generates two managed files in the repo:
//!
//! 1. `.cursor/rules/altevra.mdc` — MDC format used by Cursor for project
//!    rules. MDC = strict YAML frontmatter + Markdown body. The
//!    `ALTEVRA_MANAGED` header lives as HTML comments in the **body** (NOT in
//!    the frontmatter, because the frontmatter is parsed as YAML and arbitrary
//!    keys would break Cursor's loader).
//! 2. `.cursor/mcp.json` — JSON manifest of MCP servers, same shape as Claude
//!    Desktop's `mcpServers` map.
//!
//! Cursor (as of May 2026) has **no lifecycle hook mechanism**: there is no
//! `SessionStart` / `PreToolUse` / etc. equivalent. We therefore return an
//! empty Vec from `render_hooks()` and rely entirely on Cursor reading the
//! `.cursor/rules/altevra.mdc` rules to instruct itself to call
//! `altevra hook run …` via the CLI fallback when appropriate. If Cursor adds
//! native hooks later, wire them through this method.
//!
//! Detection: `.cursor/` directory at repo root.

use crate::base::{
    AdapterDetectionResult, GeneratedFile, InstallPlan, InstallPlanFile, InstallResult,
    InstructionRenderInput, RepairPlan, ToolAdapter, VerifyResult,
};
use altevra_hooks::universal::UniversalHook;
use altevra_skills::parser::ParsedSkill;
use altevra_skills::renderer;
use sha2::{Digest, Sha256};
use std::path::Path;
use tracing::info;

const ADAPTER_VERSION: &str = "0.1.0";

pub struct CursorAdapter;

impl CursorAdapter {
    pub fn new() -> Self {
        Self
    }

    /// Build the MDC rules file. Frontmatter stays strict YAML; the managed
    /// header is in HTML-comment form inside the body so Cursor's YAML parser
    /// doesn't choke on Altevra-specific keys.
    fn rules_mdc_content(project: Option<&str>, altevra_version: &str) -> String {
        let project_line = project
            .map(|p| format!("Project: {p}"))
            .unwrap_or_else(|| "Project: (set ALTEVRA_PROJECT env var)".to_string());

        // Build the body first (without header) so checksum is over the
        // semantically meaningful content only.
        let body = format!(
            r#"# Altevra Project Rules

{project_line}

## Session Startup

At the start of every Cursor session, Cursor should call:

```bash
altevra agent bootstrap --tool cursor --project ${{ALTEVRA_PROJECT}} --json
```

Or via MCP: `get_agent_bootstrap_packet(tool_name="cursor", project="${{ALTEVRA_PROJECT}}")`

## Quick CLI Reference

```bash
altevra updates --project ${{ALTEVRA_PROJECT}} --json          # What changed since last session
altevra skill check --all                                      # Are my skills fresh?
altevra hook run session_start --tool cursor                   # Run startup hook (CLI fallback)
altevra context --project ${{ALTEVRA_PROJECT}} --json          # Current project context
```

## Rules

- Check last updates before working.
- Warn if any skill is outdated.
- Use the CLI fallback for lifecycle events — Cursor has no native hook engine.
- Never edit `ALTEVRA_MANAGED` files manually.
- Finish session with: `altevra hook run session_end --tool cursor --project ${{ALTEVRA_PROJECT}}`
"#
        );

        let mut hasher = Sha256::new();
        hasher.update(body.as_bytes());
        let checksum = hex::encode(hasher.finalize());

        // Frontmatter must be strict YAML. Body gets the HTML-comment header.
        let frontmatter = "---\n\
             description: Altevra-managed project rules\n\
             globs: [\"**/*\"]\n\
             alwaysApply: true\n\
             ---\n\n";

        let header = format!(
            "<!-- ALTEVRA_MANAGED: true -->\n\
             <!-- source: 07-capabilities/agent-tools.yaml -->\n\
             <!-- generated_by: altevra -->\n\
             <!-- adapter: cursor -->\n\
             <!-- version: {altevra_version} -->\n\
             <!-- checksum: {checksum} -->\n\n",
        );

        format!("{frontmatter}{header}{body}")
    }

    /// Build the `.cursor/mcp.json` content. Cursor uses the same `mcpServers`
    /// shape as Claude Desktop.
    fn mcp_json_content() -> String {
        let body = serde_json::to_string_pretty(&serde_json::json!({
            "_altevra_managed": true,
            "_altevra_note": "MCP server registration generated by altevra connect. Do not edit manually.",
            "mcpServers": {
                "altevra": {
                    "command": "altevra",
                    "args": ["serve"],
                    "env": {}
                }
            }
        }))
        .unwrap_or_default();
        body
    }

    /// Classify a destination path into create/update/drifted bucket.
    fn classify_path(
        path: &Path,
        label: &str,
        creates: &mut Vec<InstallPlanFile>,
        updates: &mut Vec<InstallPlanFile>,
        drifted: &mut Vec<InstallPlanFile>,
    ) {
        if path.exists() {
            let existing = std::fs::read_to_string(path).unwrap_or_default();
            // For JSON we accept the `_altevra_managed` marker as equivalent
            // to the `ALTEVRA_MANAGED: true` header — JSON has no comments.
            let is_managed = existing.contains("ALTEVRA_MANAGED: true")
                || existing.contains("\"_altevra_managed\": true");
            if is_managed {
                updates.push(InstallPlanFile {
                    path: path.to_path_buf(),
                    action: "update".to_string(),
                    managed: true,
                    checksum: String::new(),
                    reason: Some(format!("Refresh {label}")),
                });
            } else if !existing.trim().is_empty() {
                drifted.push(InstallPlanFile {
                    path: path.to_path_buf(),
                    action: "skip (drifted — manual edits detected)".to_string(),
                    managed: false,
                    checksum: String::new(),
                    reason: Some(format!(
                        "{} exists without Altevra managed header — remove it manually first",
                        path.display()
                    )),
                });
            } else {
                creates.push(InstallPlanFile {
                    path: path.to_path_buf(),
                    action: "create".to_string(),
                    managed: true,
                    checksum: String::new(),
                    reason: Some(format!("Install {label}")),
                });
            }
        } else {
            creates.push(InstallPlanFile {
                path: path.to_path_buf(),
                action: "create".to_string(),
                managed: true,
                checksum: String::new(),
                reason: Some(format!("Install {label}")),
            });
        }
    }
}

impl Default for CursorAdapter {
    fn default() -> Self {
        Self::new()
    }
}

impl ToolAdapter for CursorAdapter {
    fn tool_name(&self) -> &'static str {
        "cursor"
    }

    fn adapter_version(&self) -> &'static str {
        ADAPTER_VERSION
    }

    fn detect(&self, repo_path: &Path) -> AdapterDetectionResult {
        let cursor_dir = repo_path.join(".cursor");
        let detected = cursor_dir.exists();
        let mut notes = vec![];
        if detected {
            notes.push(".cursor/ directory found".to_string());
        }
        AdapterDetectionResult {
            tool_name: self.tool_name().to_string(),
            detected,
            repo_path: Some(repo_path.to_path_buf()),
            notes,
        }
    }

    fn render_instructions(
        &self,
        input: InstructionRenderInput,
    ) -> anyhow::Result<Vec<GeneratedFile>> {
        let content = Self::rules_mdc_content(input.project.as_deref(), &input.altevra_version);
        // content already encodes the managed header in HTML-comment form
        // inside the body (frontmatter must stay strict YAML).
        let file = GeneratedFile::new(".cursor/rules/altevra.mdc", content);
        Ok(vec![file])
    }

    fn render_skills(&self, skills: Vec<&ParsedSkill>) -> anyhow::Result<Vec<GeneratedFile>> {
        let mut files = vec![];
        for skill in skills {
            // Use the universal skill renderer so adapter output stays in
            // lockstep with Claude Code skills layout.
            let content = renderer::render_with_header(
                skill,
                self.tool_name(),
                &altevra_skills::checksum::compute(&skill.raw),
            );
            // Skills go into Cursor's rules dir as .mdc files. To keep the
            // managed header parseable, we wrap the rendered skill in MDC
            // frontmatter.
            let mdc = format!(
                "---\n\
                 description: Altevra skill — {slug}\n\
                 globs: [\"**/*\"]\n\
                 alwaysApply: false\n\
                 ---\n\n{content}",
                slug = skill.slug()
            );
            let path = format!(".cursor/rules/altevra-skill-{}.mdc", skill.slug());
            files.push(GeneratedFile::new(path, mdc));
        }
        Ok(files)
    }

    /// Cursor has no lifecycle hook mechanism as of May 2026 — `SessionStart`,
    /// `PreToolUse`, etc. do not exist. The adapter therefore emits no files
    /// here. Lifecycle events are surfaced through the `.cursor/rules/`
    /// instructions which tell the agent to call `altevra hook run …` via the
    /// CLI fallback. Revisit if Cursor ships native hooks.
    fn render_hooks(&self, _hooks: Vec<&UniversalHook>) -> anyhow::Result<Vec<GeneratedFile>> {
        Ok(vec![])
    }

    fn build_install_plan(
        &self,
        repo_path: &Path,
        project: Option<&str>,
    ) -> anyhow::Result<InstallPlan> {
        let mut files_to_create = vec![];
        let mut files_to_update = vec![];
        let mut files_drifted = vec![];

        for (path, label) in [
            (
                repo_path.join(".cursor/rules/altevra.mdc"),
                "Cursor rules (MDC)",
            ),
            (
                repo_path.join(".cursor/mcp.json"),
                "Cursor MCP server registration",
            ),
        ] {
            Self::classify_path(
                &path,
                label,
                &mut files_to_create,
                &mut files_to_update,
                &mut files_drifted,
            );
        }

        // Skills: dynamically scan vault 06-skills/*.md — same as Claude Code
        // adapter. Each skill becomes its own MDC file under .cursor/rules/.
        let vault_skills_dir = repo_path.join("06-skills");
        let mut skills_to_install = vec![];
        if vault_skills_dir.is_dir() {
            let mut entries: Vec<_> = std::fs::read_dir(&vault_skills_dir)
                .into_iter()
                .flatten()
                .flatten()
                .collect();
            entries.sort_by_key(|e| e.path());
            for entry in entries {
                let p = entry.path();
                if p.extension().and_then(|e| e.to_str()) != Some("md") {
                    continue;
                }
                let raw = std::fs::read_to_string(&p).unwrap_or_default();
                if let Ok(skill) = altevra_skills::parser::parse_skill(&raw) {
                    let dest =
                        repo_path.join(format!(".cursor/rules/altevra-skill-{}.mdc", skill.slug()));
                    let label = format!("{} skill", skill.slug());
                    Self::classify_path(
                        &dest,
                        &label,
                        &mut files_to_create,
                        &mut files_to_update,
                        &mut files_drifted,
                    );
                    skills_to_install.push(skill);
                }
            }
        }

        Ok(InstallPlan {
            tool_name: self.tool_name().to_string(),
            project: project.map(String::from),
            files_to_create,
            files_to_update,
            files_drifted,
            skills_to_install,
            dry_run: true,
        })
    }

    fn install(&self, plan: &InstallPlan, repo_path: &Path) -> anyhow::Result<InstallResult> {
        let files_skipped: Vec<_> = plan.files_drifted.iter().map(|f| f.path.clone()).collect();

        if !plan.files_drifted.is_empty() {
            let detail: Vec<String> = plan
                .files_drifted
                .iter()
                .map(|f| f.path.display().to_string())
                .collect();
            anyhow::bail!(
                "Manual edits detected on {} — remove the file(s) first or back them up. Refusing to overwrite.",
                detail.join(", ")
            );
        }

        if plan.dry_run {
            return Ok(InstallResult {
                tool_name: self.tool_name().to_string(),
                files_created: vec![],
                files_updated: vec![],
                files_skipped,
                success: true,
                error: None,
            });
        }

        let input = InstructionRenderInput {
            tool_name: self.tool_name().to_string(),
            project: plan.project.clone(),
            repo_path: repo_path.to_path_buf(),
            altevra_version: ADAPTER_VERSION.to_string(),
        };

        let mut to_write: Vec<GeneratedFile> = vec![];
        to_write.extend(self.render_instructions(input)?);

        // mcp.json doesn't fit cleanly into render_instructions or
        // render_hooks (Cursor has no hooks). Emit it inline here.
        let mcp = GeneratedFile::new(".cursor/mcp.json", Self::mcp_json_content());
        to_write.push(mcp);

        to_write.extend(self.render_skills(plan.skills_to_install.iter().collect())?);

        let creates: std::collections::HashSet<_> = plan
            .files_to_create
            .iter()
            .map(|f| f.path.clone())
            .collect();
        let updates: std::collections::HashSet<_> = plan
            .files_to_update
            .iter()
            .map(|f| f.path.clone())
            .collect();

        let mut files_created = vec![];
        let mut files_updated = vec![];
        for gen in &to_write {
            let dest = repo_path.join(&gen.path);
            if creates.contains(&dest) {
                if let Some(parent) = dest.parent() {
                    std::fs::create_dir_all(parent)?;
                }
                std::fs::write(&dest, &gen.content)?;
                info!("Created managed file: {}", dest.display());
                files_created.push(dest);
            } else if updates.contains(&dest) {
                if let Some(parent) = dest.parent() {
                    std::fs::create_dir_all(parent)?;
                }
                std::fs::write(&dest, &gen.content)?;
                info!("Updated managed file: {}", dest.display());
                files_updated.push(dest);
            }
        }

        Ok(InstallResult {
            tool_name: self.tool_name().to_string(),
            files_created,
            files_updated,
            files_skipped,
            success: true,
            error: None,
        })
    }

    fn verify(&self, repo_path: &Path) -> anyhow::Result<VerifyResult> {
        let mut issues = vec![];
        let mut drifted = vec![];

        // The MDC rules file uses the canonical `ALTEVRA_MANAGED: true` marker
        // in its body.
        let rules_path = repo_path.join(".cursor/rules/altevra.mdc");
        if !rules_path.exists() {
            issues.push(format!("Missing: {}", rules_path.display()));
        } else {
            let content = std::fs::read_to_string(&rules_path).unwrap_or_default();
            if !content.contains("ALTEVRA_MANAGED: true") {
                issues.push(format!(
                    "Drift detected (no managed header): {}",
                    rules_path.display()
                ));
                drifted.push(rules_path);
            }
        }

        // mcp.json uses the `_altevra_managed` JSON marker.
        let mcp_path = repo_path.join(".cursor/mcp.json");
        if !mcp_path.exists() {
            issues.push(format!("Missing: {}", mcp_path.display()));
        } else {
            let content = std::fs::read_to_string(&mcp_path).unwrap_or_default();
            if !content.contains("\"_altevra_managed\": true") {
                issues.push(format!(
                    "Drift detected (no managed marker): {}",
                    mcp_path.display()
                ));
                drifted.push(mcp_path);
            }
        }

        Ok(VerifyResult {
            tool_name: self.tool_name().to_string(),
            all_ok: issues.is_empty(),
            issues,
            drifted_files: drifted,
        })
    }

    fn repair(&self, _repo_path: &Path) -> anyhow::Result<RepairPlan> {
        Ok(RepairPlan {
            tool_name: self.tool_name().to_string(),
            actions: vec![
                "Re-run: altevra connect --tool cursor to restore managed files".to_string(),
            ],
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn test_render_instructions_returns_managed_mdc() {
        let adapter = CursorAdapter::new();
        let input = InstructionRenderInput {
            tool_name: "cursor".to_string(),
            project: Some("altevra".to_string()),
            repo_path: std::path::PathBuf::from("/tmp"),
            altevra_version: "0.1.0".to_string(),
        };
        let files = adapter.render_instructions(input).unwrap();
        assert_eq!(files.len(), 1);
        let f = &files[0];
        assert_eq!(
            f.path,
            std::path::PathBuf::from(".cursor/rules/altevra.mdc")
        );
        // Frontmatter must come first and contain alwaysApply / globs.
        assert!(f.content.starts_with("---\n"), "missing MDC frontmatter");
        assert!(f.content.contains("alwaysApply: true"));
        assert!(f.content.contains("globs:"));
        // Managed header lives in body, NOT in frontmatter.
        let frontmatter_end = f.content.find("---\n\n").unwrap();
        let frontmatter = &f.content[..frontmatter_end];
        assert!(
            !frontmatter.contains("ALTEVRA_MANAGED"),
            "managed header must NOT be in the YAML frontmatter (it would break Cursor's parser)"
        );
        assert!(
            f.content.contains("ALTEVRA_MANAGED: true"),
            "managed header missing from body"
        );
        assert!(f.content.contains("adapter: cursor"));
        assert!(
            !f.content.contains("generated_at"),
            "header must not contain generated_at"
        );
    }

    #[test]
    fn test_render_hooks_is_empty() {
        let adapter = CursorAdapter::new();
        let files = adapter.render_hooks(vec![]).unwrap();
        assert!(
            files.is_empty(),
            "Cursor has no lifecycle hook engine — render_hooks must return empty"
        );
    }

    #[test]
    fn test_detect_picks_up_cursor_dir() {
        let adapter = CursorAdapter::new();
        let tmp = tempdir().unwrap();
        std::fs::create_dir_all(tmp.path().join(".cursor")).unwrap();
        let result = adapter.detect(tmp.path());
        assert!(result.detected, "detect() should fire on .cursor/ dir");
        assert!(result.notes.iter().any(|n| n.contains(".cursor/")));
    }

    #[test]
    fn test_build_install_plan_is_non_empty() {
        let adapter = CursorAdapter::new();
        let tmp = tempdir().unwrap();
        let plan = adapter
            .build_install_plan(tmp.path(), Some("altevra"))
            .unwrap();
        assert!(plan.dry_run);
        assert_eq!(plan.tool_name, "cursor");
        // At minimum altevra.mdc + mcp.json should be planned (no skills in tmp).
        assert!(plan.files_to_create.len() + plan.files_to_update.len() >= 2);
    }

    #[test]
    fn test_mcp_json_is_valid_json_with_managed_marker() {
        let raw = CursorAdapter::mcp_json_content();
        let parsed: serde_json::Value =
            serde_json::from_str(&raw).expect(".cursor/mcp.json must be valid JSON");
        assert_eq!(parsed["_altevra_managed"], serde_json::json!(true));
        assert!(parsed["mcpServers"]["altevra"]["command"].is_string());
    }

    #[test]
    fn test_drift_detection_refuses_overwrite() {
        let adapter = CursorAdapter::new();
        let tmp = tempdir().unwrap();
        std::fs::create_dir_all(tmp.path().join(".cursor/rules")).unwrap();
        // Hand-written rules file without the managed header.
        std::fs::write(
            tmp.path().join(".cursor/rules/altevra.mdc"),
            "---\ndescription: my own rules\n---\n\n# manual\n",
        )
        .unwrap();

        let plan = adapter.build_install_plan(tmp.path(), None).unwrap();
        assert!(
            !plan.files_drifted.is_empty(),
            "expected drift detection on hand-edited altevra.mdc"
        );

        let err = adapter.install(&plan, tmp.path()).unwrap_err();
        assert!(err.to_string().to_lowercase().contains("manual edits"));
    }

    #[test]
    fn test_install_then_verify_round_trip() {
        let adapter = CursorAdapter::new();
        let tmp = tempdir().unwrap();
        let mut plan = adapter
            .build_install_plan(tmp.path(), Some("test"))
            .unwrap();
        plan.dry_run = false;

        let result = adapter.install(&plan, tmp.path()).unwrap();
        assert!(result.success);
        assert!(tmp.path().join(".cursor/rules/altevra.mdc").exists());
        assert!(tmp.path().join(".cursor/mcp.json").exists());

        let v = adapter.verify(tmp.path()).unwrap();
        assert!(v.all_ok, "verify failed: {:?}", v.issues);
    }
}
